### ISSUE TITLE
Feature request: Toggle buildings

### ISSUE THREAD

**Issue by originalfoo** [keallu/CSL-ToggleIt#1]
(Moved from https://github.com/keallu/CSL-HideIt/issues/8#issuecomment-541348338)

Similar to what this now-defunct mod did: https://steamcommunity.com/sharedfiles/filedetails/?id=417926819

![image](https://user-images.githubusercontent.com/1386719/66708047-51f2c580-ed42-11e9-822e-e1177289be9b.png)

**Comment by keallu** [comment]
That's a good idea. I've added it to my todo list.
