### ISSUE TITLE
Minor conflict: Grid be Gone mod

### ISSUE THREAD

**Issue by originalfoo** [keallu/CSL-ToggleIt#2]
[Grid be Gone](https://steamcommunity.com/sharedfiles/filedetails/?id=1540147921u), as it's name suggests, toggles the zoning grid/color display.

If both mods are enabled, and in particular if the feint overlay is being hidden when grid hidden, there seems to be some disruption of state management in both mods if both mods are being used to toggle zoning grid/color.

Suggestion: If Grid be Gone mod is enabled (workshop ID: 1540147921), disable zoning grid/color features of Toggle It, or find some way to sync state of both mods.

**Comment by originalfoo** [comment]
A similar issue occurs with [Hide Selectors](https://steamcommunity.com/sharedfiles/filedetails/?id=1536223783u) mod. Workshop id: 1536223783

**Comment by keallu** [comment]
Why use Grid be Gone and Hide Selectors if you have Toggle It! that can do everything these two mods can?

Toggle It! is a replacement for these two mods.
