### ISSUE TITLE
Icon buttons?

### ISSUE THREAD

**Issue by originalfoo** [keallu/CSL-ToggleIt#4]
Would it be possible to associate each toggleable feature with an icon, so that buttons could show icons rather than letters?

For exmaple, a pipe for the Water Pipes togle?

I've no idea what sort of icon could represent district names, so I imagine this would be tricky to implent... :/

**Comment by keallu** [comment]
I do like the idea but yes, it can require quite a lot of icons and it takes time. I think most people uses key mappings instead of the toolbar but I will add it to my feature list and see what the future brings :)

**Comment by keallu** [comment]
You can now setup buttons with your own selected characters.
